#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

exec </dev/tty >/dev/tty 2>&1

################################################################################

source "$HOME/bin/include/srcds_pid"
source "$HOME/bin/include/srcds.conf"
source "$HOME/bin/include/srcds_bots"
source "$HOME/bin/include/data_usage"
source "$HOME/bin/include/srcds_mods"
source "$HOME/bin/include/srcds_logs"
source "$HOME/bin/include/system_info"
source "$HOME/bin/include/srcds_update"
source "$HOME/bin/include/srcds_active"
source "$HOME/bin/include/srcds_fastdl"
source "$HOME/bin/include/srcds_console"
source "$HOME/bin/include/srcds_crontab"
source "$HOME/bin/include/srcds_options"
source "$HOME/bin/include/random_password"

################################################################################
# process id
################################################################################

srcds_pid

################################################################################
# srcds version
################################################################################

# not found
if [[ ! -f "$HOME/bin/version" ]]; then
  # update version file
  LOC_V=$(wc -l "$HOME"/bin/srcds "$HOME"/bin/include/*_* 2>/dev/null | grep "total" | awk '{ print $1 }')
  echo "v$LOC_V" >"$HOME/bin/version"
fi

SCAN_FILE="$HOME/bin/srcds"
VERSION_FILE="$HOME/bin/version"

if [[ -z "$VERSION_FILE" ]]; then
  VERSION_FILE="Update please.."
fi

# ensure version file exists or initialize it
if [[ ! -f "$VERSION_FILE" ]]; then
  SCRIPT_VERSION="v$([[ -f "$SCAN_FILE" ]] && wc -l <"$SCAN_FILE" || echo 'N/A')"
  echo "$SCRIPT_VERSION" >"$VERSION_FILE"
fi

# read version, remove whitespace
SCRIPT_VERSION=$(<"$VERSION_FILE")
SCRIPT_VERSION="${SCRIPT_VERSION//[[:space:]]/}"

################################################################################
# SRCDS start
################################################################################

srcds_start() {
  # if already running
  if screen -list 2>/dev/null | grep -q '\.srcds_screen'; then
    SRCDS_PID_INFO="$(ps -p "$(pgrep srcds_linux 2>/dev/null)" 2>/dev/null | column -t)"
    dialog --no-collapse --msgbox "Server already running!
$SRCDS_PID_INFO" 0 0
    # return to menu
    return 1
  fi
  # start server ###############################################################
  bash "$HOME"/bin/include/start_srcds
  ##############################################################################
  dialog --msgbox "Server and daemon started!" 5 32
}

################################################################################
# SRCDS stop
################################################################################

srcds_stop() {
  if [[ ! -z "$SRCDS_PID" ]]; then
    dialog --yesno "Stop server and daemon?" 5 29
    [[ ! $? == 0 ]] && return 1
    # stop server ##############################################################
    bash "$HOME"/bin/include/stop_srcds
    ############################################################################
    dialog --msgbox "Server and daemon stopped!" 5 32
  else
    dialog --msgbox "Server is not running!" 5 28
  fi
}

################################################################################
# srcds configurations
################################################################################

function srcds_configs() {
  MENU="SRCDS Configurations"

  CONFIG_DIRS=(
    "$HOME/bin/include"
    "$HOME/HLstatsX"
    "$SRCDS_DIR/$SERVER_GAME/cfg"
    "$SRCDS_DIR/$SERVER_GAME/maps"
    "$SRCDS_DIR/$SERVER_GAME/cfg/cssdm"
    "$SRCDS_DIR/$SERVER_GAME/cfg/metamod"
    "$SRCDS_DIR/$SERVER_GAME/cfg/sourcemod"
    "$SRCDS_DIR/$SERVER_GAME/addons/sourcemod/gamedata"
    "$SRCDS_DIR/$SERVER_GAME/addons/sourcemod/configs"
    "$SRCDS_DIR/$SERVER_GAME/addons/sourcemod/configs/mapscfg/"
  )

  OPTIONS=()
  FILES=()
  i=0
  MAXLEN=0

  for DIR in "${CONFIG_DIRS[@]}"; do
    [[ -d "$DIR" ]] || continue
    while IFS= read -r FILE; do
      LABEL="${FILE#$SRCDS_DIR/}"
      OPTIONS+=("$i" "$LABEL")
      FILES[$i]="$FILE"

      LEN=${#LABEL}
      ((LEN > MAXLEN)) && MAXLEN=$LEN

      ((i++))
    done < <(
      find "$DIR" -maxdepth 1 -type f \
        \( -name "*.cfg" -o -name "*.conf" -o -name "*.ini" -o -name "*.txt" -o -name "*.res" \) |
        sort
    )
  done

  HEIGHT="25"
  CHOICE_HEIGHT="20"
  WIDTH=$((MAXLEN + 12))

  CHOICE=$(dialog --clear \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  STATUS=$?
  clear

  # cancel
  if [[ $STATUS -ne 0 ]]; then
    return
  fi

  nano "${FILES[$CHOICE]}"
  srcds_configs
}

################################################################################
# srcds menu
################################################################################

# screenlog.0
ACTIVE_STATUS="$(tail -100 "$HOME"/bin/include/screenlog.0 2>/dev/null | grep -A7 "hostname" | tail -8 | tr -d ')\r')"
ACTIVE_HOSTNAME="$(grep "hostname" "$SRCDS_DIR"/"$SERVER_GAME"/cfg/server.cfg 2>/dev/null | awk -F'"' '{ print $2 }')"

# if no hostname configuration
if [[ -z "$ACTIVE_HOSTNAME" ]]; then
  OUTPUT="$SRCDS_DIR/$SERVER_GAME/cfg/server.cfg not found, create new one?"
  OUTPUT_WIDTH="$(echo "$(echo "$OUTPUT" | wc -L)+6" | bc 2>/dev/null)"
  dialog --yesno "$OUTPUT" 5 "$OUTPUT_WIDTH"
  [[ ! $? == 0 ]] && return 1
  echo "Creating new server.cfg.."
  # create server.cfg with default hostname
  echo "hostname '"'Source Dedicated Server :: SRCDS based'"'" >"$SRCDS_DIR"/"$SERVER_GAME"/cfg/server.cfg
fi

# if zero
if [[ -z "$ACTIVE_HOSTNAME" ]]; then
  ACTIVE_HOSTNAME="No server name!"
fi

ACTIVE_AMOUNT="$(echo "$ACTIVE_STATUS" | grep "players" | egrep -o "[0-9]+" | head -2 | awk '{sum += $1} END {print sum}' 2>/dev/null)"
ACTIVE_IRL_AMOUNT="$(echo "$ACTIVE_STATUS" | grep "players" | awk '{ print $3 }' | tr -d '(')"
ACTIVE_BOT_AMOUNT="$(echo "$ACTIVE_STATUS" | grep "players" | awk '{ print $5 }' | tr -d '(')"
ACTIVE_MAX_AMOUNT="$(echo "$ACTIVE_STATUS" | grep "players" | awk '{ print $7 }' | tr -d '(')"
ACTIVE_MAP="$(echo "$ACTIVE_STATUS" | grep "map" | awk '{ print $3 }')"
ACTIVE_WAN="$(echo "$ACTIVE_STATUS" | grep 'udp/ip' | awk '{print $NF}')"

function update_active() {
  # if greater than n
  if [[ "$ACTIVE_AMOUNT" -gt "0" ]]; then
    # update active players
    grep -A"$ACTIVE_AMOUNT" "userid" "$HOME"/bin/include/screenlog.0 2>/dev/null | grep -v "rcon" | tail -"$ACTIVE_AMOUNT" | tr -d '#' | column -t >/tmp/usrid.tmp
  fi
}
update_active

################################################################################

SCREEN_LOG="$HLSTATSX_DIR/screenlog.0"
SCREEN_SESSION="srcds_screen"
SCREEN_MAXLINES="9000"

# trim screen log
if [ -f "$SCREEN_LOG" ] && [ "$(wc -l <"$SCREEN_LOG")" -ge "$SCREEN_MAXLINES" ]; then
  screen -S "$SCREEN_SESSION" -X log off
  echo "$(tail -369 "$SCREEN_LOG" 2>/dev/null)" >"$SCREEN_LOG"
  screen -S "$SCREEN_SESSION" -X log on
fi

# srcds pid status
if [[ "$SRCDS_PID" > "0" ]]; then
  ACTIVE_WAN="${ACTIVE_WAN}:${SERVER_PORT}"
  SRCDS_STATUS="OK"
else
  ACTIVE_MAP="N/A"
  ACTIVE_WAN="N/A"
  ACTIVE_PLAYERS="N/A"
  SRCDS_STATUS="NO"
fi

# screen pid status
if [[ "$SCREEN_PID" > "0" ]]; then
  SCREEN_STATUS="OK"
else
  SCREEN_STATUS="NO"
fi

# if pid is running
if [[ "$HLSTATSX_PID" -eq "1" ]]; then
  HLSTATSX_STATUS="hlstatsx OK"

  ##############################################################################
  # install extra
  ##############################################################################

  # if not found
  if [[ ! -f "$SRCDS_DIR"/"$SERVER_GAME"/addons/sourcemod/plugins/disabled/hlstatsx.smx ]]; then
    # copy hlstatsx.smx to disabled
    cp "$HOME"/bin/include/extra/addons/sourcemod/plugins/hlstatsx.smx "$SRCDS_DIR"/"$SERVER_GAME"/addons/sourcemod/plugins/disabled/hlstatsx.smx
  fi
fi

################################################################################
# main menu
################################################################################

# if no pid exist but installed
if [[ "$HLSTATSX_PID" -eq "0" && -d "$HOME"/HLstatsX ]]; then
  HLSTATSX_STATUS="hlstatsx NO"
  # if no pid exist and not installed
elif [[ "$HLSTATSX_PID" -eq "0" && ! -d "$HOME"/HLstatsX ]]; then
  HLSTATSX_STATUS=""
fi

HEIGHT="24"
CHOICE_HEIGHT="10"
BACKTITLE="SRCDS Menu $SCRIPT_VERSION"
MENU="Host.....: $ACTIVE_HOSTNAME
Address..: ${ACTIVE_WAN:?}
Map......: $ACTIVE_MAP
Players..: ${ACTIVE_IRL_AMOUNT:-0}/${ACTIVE_BOT_AMOUNT:-0}/${ACTIVE_MAX_AMOUNT:-0}
CPU......: ${LOAD_PCT}% ${CPU_TEMP}°C
Memory...: ${TOTAL_PCT}% ${TOTAL_USED_MEM_MB}/${TOTAL_MEM_MB} MB
Services.: screen $SCREEN_STATUS srcds $SRCDS_STATUS $HLSTATSX_STATUS"
WIDTH="$(($(echo "$MENU" | wc -L) + 5))"

# if zero
if [[ "$WIDTH" -lt "51" ]]; then
  WIDTH="51"
fi

OPTIONS=(
  1 "Console      Show SRCDS screen console"
  2 "Active       Active players"
  3 "Start        Launch source server"
  4 "Stop         Stop source server"
  5 "Logs         View server logs"
  6 "Config       Edit server configurations"
  7 "Mods         MetaMod SourceMod HLstatsX"
  8 "Tools        Server tools & options"
  9 "Update       Pull updates from github"
  i "System       System information"
  0 "Exit         Quit program"
)

CHOICE=$(dialog --clear \
  --backtitle "$BACKTITLE" \
  --no-cancel \
  --menu "$MENU" \
  $HEIGHT $WIDTH $CHOICE_HEIGHT \
  "${OPTIONS[@]}" \
  2>&1 >/dev/tty)

clear
case $CHOICE in
"1") srcds_console ;;
"2") srcds_active ;;
"3") srcds_start ;;
"4") srcds_stop ;;
"5") srcds_logs ;;
"6") srcds_configs ;;
"7") srcds_mods ;;
"8") srcds_options ;;
"9") srcds_update ;;
"i") srcds_system ;;
"0") clear && exit 0 ;;
esac

# restart the script by exec
exec /bin/bash "$0" "$@"
clear

# END
