#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

function random_password() {
  dialog --inputbox "Enter the number of characters:" 7 36 10 2>/tmp/psam.tmp
  EXIT_STATUS=$?
  PASS_AMOUNT="$(cat /tmp/psam.tmp 2>/dev/null)"

  # go back to main menu if Cancel/ESC or empty input
  if [ $EXIT_STATUS -ne 0 ] || [[ -z "$PASS_AMOUNT" ]]; then
    continue # return to main menu loop
  fi

  PASS_LENGTH=${1:-$PASS_AMOUNT}
  clear
  echo "Password length: $PASS_LENGTH

$(base64 </dev/urandom | head -c $PASS_LENGTH | rev | cut -c 2- | rev | tr -d '\n')
  "
  exit 0 # only exit if password was actually generated
}

# END
