#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

# tools & options
function srcds_options() {
  while true; do
    HEIGHT="13"
    WIDTH="54"
    CHOICE_HEIGHT="6"
    MENU="SRCDS Tools & Options"

    OPTIONS=(
      1 "Bots             Bot management options"
      2 "Data Usage       Monitor network data"
      3 "crontab          Manage scheduled tasks"
      4 "ncdu             NCurses disk usage viewer"
      5 "FastDL           Faster map downloads"
      6 "Random           Password generator"
    )

    CHOICE=$(dialog --clear \
      --menu "$MENU" \
      $HEIGHT $WIDTH $CHOICE_HEIGHT \
      "${OPTIONS[@]}" \
      3>&1 1>&2 2>&3)
    EXIT_STATUS=$?
    clear

    # exit loop if Cancel/ESC pressed
    if [ $EXIT_STATUS -ne 0 ]; then
      break
    fi

    case $CHOICE in
    "1") srcds_bots ;;      # bots
    "2") data_usage ;;      # data usage
    "3") srcds_crontab ;;   # crontab
    "4") ncdu "$HOME" ;;    # ncurses
    "5") srcds_fastdl ;;    # fastdl menu
    "6") random_password ;; # random password generate
    esac
  done
  return 0
}

# END
