#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

# hlstatsx warden
if [[ "$(egrep -c "Timeout|stalled|Can't|failed" "$HOME"/HLstatsX/logs/hlstats_* 2>/dev/null)" -gt "0" ]]; then
  HLSTATSX_LOG_NAME="$(ls -ltr "$HOME"/HLstatsX/logs/ | awk '{ print $NF }' | tail -1)"
  # log output
  echo "SRCDS: timeouts, stalled, fails detected..!" >>"$HOME"/HLstatsX/logs/"$HLSTATSX_LOG_NAME"
  # log output
  echo "SRCDS: restarting hlstatsx daemon..!" >>"$HOME"/HLstatsX/logs/"$HLSTATSX_LOG_NAME"
  # stop stats
  cd "$HLSTATSX_DIR" && ./run_hlstats restart &>/dev/null
fi

################################################################################

# END
