#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

function srcds_logs() {

  # total log lines
  TOTAL_LINES="$(wc -l "$HOME"/bin/include/logs/cron.log "$HOME"/bin/include/logs/screenlog.0 "$SRCDS_DIR"/debug.log "$HOME"/Steam/logs/*.txt.log "$SRCDS_DIR"/"$SERVER_GAME"/logs/*.log "$SRCDS_DIR"/"$SERVER_GAME"/addons/sourcemod/logs/*.log "$HLSTATSX_DIR"/logs/hlstats* 2>/dev/null | tail -1 | awk '{ print $1 }')"
  TOTAL_SIZE=$(stat -c%s "$HOME"/bin/include/logs/cron.log "$HOME"/bin/include/logs/screenlog.0 "$SRCDS_DIR"/debug.log "$HOME"/Steam/logs/*.txt.log "$SRCDS_DIR"/"$SERVER_GAME"/logs/*.log "$SRCDS_DIR"/"$SERVER_GAME"/addons/sourcemod/logs/*.log "$HLSTATSX_DIR"/logs/hlstats* 2>/dev/null | awk '{sum += $1} END {print sum}')

  if [[ $TOTAL_SIZE -ge 1073741824 ]]; then
    TOTAL_SIZE="$(awk "BEGIN {printf \"%.2f\", $TOTAL_SIZE/1024/1024/1024}") GB"
  elif [[ $TOTAL_SIZE -ge 1048576 ]]; then
    TOTAL_SIZE="$(awk "BEGIN {printf \"%.2f\", $TOTAL_SIZE/1024/1024}") MB"
  elif [[ $TOTAL_SIZE -ge 1024 ]]; then
    TOTAL_SIZE="$(awk "BEGIN {printf \"%.2f\", $TOTAL_SIZE/1024}") KB"
  else
    # if zero
    if [[ -z "$TOTAL_SIZE" ]]; then
      TOTAL_SIZE="0"
    fi
    TOTAL_SIZE="$TOTAL_SIZE bytes"
  fi

  HEIGHT="15"
  WIDTH="48"
  CHOICE_HEIGHT="8"
  MENU="SRCDS Logs - Lines: ${TOTAL_LINES:-0} Size: ${TOTAL_SIZE:-0}"

  OPTIONS=(
    1 "Server           View SRCDS log"
    2 "Stats            View HLstatsX log"
    3 "Addons           View SourceMod logs"
    4 "Steam            View Steam logs"
    5 "Debug            View debug.log"
    6 "Screen           View screenlog.0"
    7 "Cron             View cron.log"
    0 "Purge            Delete all logs"
  )

  CHOICE=$(dialog --clear \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  "1")

    SERVER_LOG=$(ls -t "$SRCDS_DIR"/"$SERVER_GAME"/logs/*.log 2>/dev/null | head -n 1)
    if [ -z "$SERVER_LOG" ]; then
      dialog --msgbox "No log files found" 5 24
    else
      dialog --tailbox "$SERVER_LOG" 30 141
    fi
    srcds_logs # go back to logs menu
    ;;

  "2")

    HLSTATSX_LOG=$(ls -t "$HLSTATSX_DIR"/logs/hlstats* 2>/dev/null | head -n 1)
    if [ -z "$HLSTATSX_LOG" ]; then
      dialog --msgbox "No log files found" 5 24
    else
      dialog --tailbox "$HLSTATSX_LOG" 30 121
    fi
    srcds_logs # go back to logs menu
    ;;

  "3")

    SOURCEMOD_LOG=$(ls -t "$SRCDS_DIR"/"$SERVER_GAME"/addons/sourcemod/logs/L*.log 2>/dev/null | head -n 1)
    SOURCEMOD_ERROR_LOG=$(ls -t "$SRCDS_DIR"/"$SERVER_GAME"/addons/sourcemod/logs/errors*.log 2>/dev/null | head -n 1)
    if [ -z "$SOURCEMOD_LOG" ]; then
      dialog --msgbox "No log files found" 5 24
    else
      dialog --tailbox "$SOURCEMOD_LOG" 30 121
      dialog --tailbox "$SOURCEMOD_ERROR_LOG" 30 121
    fi
    srcds_logs # go back to logs menu
    ;;

  "4")

    LOG_DIR="$HOME/Steam/logs"

    mapfile -t FILES < <(
      find "$LOG_DIR" -maxdepth 1 -type f \( -name "*.txt" -o -name "*log*" \)
    )

    if [ ${#FILES[@]} -eq 0 ]; then
      dialog --msgbox "No log files found" 5 24
      exit 1
    fi

    MENU_ITEMS=()
    for f in "${FILES[@]}"; do
      MENU_ITEMS+=("$f" "")
    done

    WIDTH="$(echo "$(echo "$MENU_ITEMS" | wc -L)+20" | bc 2>/dev/null)"
    CHOICE=$(dialog --stdout \
      --title "Steam log files" \
      --menu "Select a file:" 0 "$WIDTH" 17 \
      "${MENU_ITEMS[@]}")
    # nano choice
    if [[ -n "$CHOICE" ]]; then
      nano "$CHOICE"
    fi
    srcds_logs # go back to logs menu
    ;;

  "5")

    DEBUG_LOGS=$(ls -t "$SRCDS_DIR"/debug.log 2>/dev/null | head -n 1)
    if [ -z "$DEBUG_LOGS" ]; then
      dialog --msgbox "No log files found" 5 24
    else
      dialog --tailbox "$DEBUG_LOGS" 30 121
    fi
    srcds_logs # go back to configs menu
    ;;

  "6")

    SCREEN_LOGS=$(ls -t "$HOME"/bin/include/logs/screenlog.0 2>/dev/null | head -n 1)
    if [ -z "$SCREEN_LOGS" ]; then
      dialog --msgbox "No log files found" 5 24
    else
      # keep n lines
      echo "$(tail -1440 "$HOME"/bin/include/logs/screenlog.0 2>/dev/null)" >"$HOME"/bin/include/logs/screenlog.0
      dialog --tailbox "$SCREEN_LOGS" 30 121
    fi
    srcds_logs # go back to configs menu
    ;;

  "7")

    CRON_LOGS="$(cat "$HOME"/bin/include/logs/cron.log 2>/dev/null | sort | uniq)"
    if [ -z "$CRON_LOGS" ]; then
      dialog --msgbox "No log files found" 5 24
    else
      # keep n lines
      echo "$(tail -1440 "$HOME"/bin/include/logs/cron.log 2>/dev/null)" >"$HOME"/bin/include/logs/cron.log
      dialog --msgbox "$CRON_LOGS" 0 0
    fi
    srcds_logs # go back to configs menu
    ;;

    # delete all logs

  "0")

    if screen -list 2>/dev/null | grep -q '\.srcds_screen'; then
      dialog --msgbox "Server already running!" 5 28
      return 1
    fi
    # remove logs
    rm "$HOME"/bin/include/logs/cron.log "$HOME"/bin/include/logs/screenlog.0 "$SRCDS_DIR"/debug.log "$HOME"/Steam/logs/*.txt.log "$SRCDS_DIR"/"$SERVER_GAME"/logs/*.log "$SRCDS_DIR"/"$SERVER_GAME"/addons/sourcemod/logs/*.log "$HLSTATSX_DIR"/logs/hlstats* &>/dev/null
    ;;
  esac
}

# END
