#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

function srcds_crontab() {
  dialog --msgbox "Awards generation and database cleanup (daily at midnight)
Server restart check (every 5 minutes)
Daemon restart check (every 5 minutes)

15 00 * * * cd $HOME/HLstatsX && ./hlstats-awards.pl >>$HOME/bin/include/logs/cron.log 2>&1
*/5 * * * * cd $HOME/HLstatsX && ./run_hlstats start >>$HOME/bin/include/logs/cron.log 2>&1
*/5 * * * * cd $HOME/bin/include && ./start_srcds >>$HOME/bin/include/logs/cron.log 2>&1" 11 111
  crontab -e
}

# END
