#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

function srcds_console() {
  if ! screen -list 2>/dev/null | grep -q '\.srcds_screen'; then
    dialog --msgbox "Server not running!" 5 24
    return 1
  fi
  dialog --msgbox "CTRL A+D for soft exit (detach)" 5 36
  clear && screen -r -q srcds_screen && clear
}

# END
