#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

# hlstatsx warden
HLSTATSX_LOGS="$(egrep -c "Timeout|stalled|Can't|failed" "$HOME"/HLstatsX/logs/hlstats_* 2>/dev/null | awk -F: '{ print $NF }' 2>/dev/null | tail -1 2>/dev/null)"
# if zero
if [[ -z "$HLSTATSX_LOGS" ]]; then
  HLSTATSX_LOGS="0"
fi
# if any issues
if [[ "$HLSTATSX_LOGS" -gt "0" ]]; then
  # log output
  echo "-- Timeouts, Stalled, Fails detected..! @ $(date | xargs)" >>"$HOME"/bin/include/cron.log
  echo "++ Restarting hlstatsx daemon..!" >>"$HOME"/bin/include/cron.log
  # keep old logs
  cat "$HOME"/HLstatsX/logs/hlstats_* | awk 'seen[$0]++' >>"$HOME"/HLstatsX/logs/hlstats_old
  # keep lines
  echo "$(tail -1000 "$HOME"/HLstatsX/logs/hlstats_old)" >"$HOME"/HLstatsX/logs/hlstats_old
  # stop stats
  cd "$HLSTATSX_DIR" && ./run_hlstats restart &>/dev/null
fi

# END
