#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

source "$HOME/bin/include/srcds.conf"
source "$HOME/bin/include/srcds_warden"

################################################################################

LOGFILE="$HOME/bin/include/screenlog.0"

# if not running
if ! screen -list 2>/dev/null | grep -q "[.]srcds_screen"; then
  # start stats
  cd "$HLSTATSX_DIR" && ./run_hlstats start
  # start server with screen logging to fixed location
  screen -L -Logfile "$LOGFILE" -S srcds_screen -dm \
    "$SRCDS_DIR"/srcds_run -debug \
    -usercon -console -game "$SERVER_GAME" \
    -port "$SERVER_PORT" +map "$SERVER_MAP" \
    +maxplayers "$SERVER_MAX" +ip "$SERVER_IP"
  dialog --msgbox "Server and daemon started!" 5 32
else
  echo "Server is already running on port $SERVER_PORT"
fi

# END
