#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

source "$HOME/bin/include/srcds.conf"

################################################################################

# stop stats
cd "$HLSTATSX_DIR" && ./run_hlstats stop &>/dev/null
# stop server
screen -X -S srcds_screen quit &>/dev/null
if [[ "$SRCDS_PID" -gt "0" ]]; then
  kill -9 "$SRCDS_PID" &>/dev/null
fi
WIDTH="$(echo "$(echo "Stopped SRCDS and HLstatsX ($SRCDS_PID/$SCREEN_PID)" | wc -L)+4" | bc 2>/dev/null)"
dialog --msgbox "Stopped SRCDS and HLstatsX ($SRCDS_PID/$SCREEN_PID)" 5 "$WIDTH"

# END
