#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

################################################################################
# system
################################################################################

# users, host, uptime, load, ip, cpu model
USERS=$(who | wc -l)
HOST=$(hostname)
UPTIME=$(uptime -p)
LOAD=$(cut -d' ' -f1-3 /proc/loadavg)
IP=$(hostname -I | awk '{print $1}')
CPU_MODEL=$(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo | xargs)

# load, srcds, screen pid
SYSTEM_LOAD="$(awk '{ print $1,$2,$3 }' /proc/loadavg)"
# get number of CPU cores
CPU_CORES=$(nproc)

# read individual load numbers into variables
read LOAD1 LOAD2 LOAD3 <<<"$SYSTEM_LOAD"

# calculate average load
AVG_LOAD=$(awk -v l1="$LOAD1" -v l2="$LOAD2" -v l3="$LOAD3" 'BEGIN { print (l1+l2+l3)/3 }')
# convert to percentage
LOAD_PCT=$(awk -v avg="$AVG_LOAD" -v cores="$CPU_CORES" 'BEGIN { printf "%.2f", (avg/cores)*100 }')

################################################################################
# thermals
################################################################################

BATTERY_TEMP_RAW=$(</sys/class/thermal/thermal_zone0/temp)
CPU_TEMP_RAW=$(</sys/class/thermal/thermal_zone1/temp)

BATTERY_TEMP=$((BATTERY_TEMP_RAW / 1000))
CPU_TEMP=$((CPU_TEMP_RAW / 1000))

BATTERY_TYPE=$(</sys/class/thermal/thermal_zone0/type)
CPU_TYPE=$(</sys/class/thermal/thermal_zone1/type)

################################################################################
# memory
################################################################################

# read RAM
MEM_TOTAL=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
MEM_AVAILABLE=$(awk '/MemAvailable/ {print $2}' /proc/meminfo)
# read swap
SWAP_TOTAL=$(awk '/SwapTotal/ {print $2}' /proc/meminfo)
SWAP_FREE=$(awk '/SwapFree/ {print $2}' /proc/meminfo)
SWAP_USED=$((SWAP_TOTAL - SWAP_FREE))
# RAM used
MEM_USED=$((MEM_TOTAL - MEM_AVAILABLE))
# convert to MB
MEM_TOTAL_MB=$((MEM_TOTAL / 1024))
MEM_USED_MB=$((MEM_USED / 1024))
SWAP_TOTAL_MB=$((SWAP_TOTAL / 1024))
SWAP_USED_MB=$((SWAP_USED / 1024))
# total memory
TOTAL_MEM_MB=$((MEM_TOTAL_MB + SWAP_TOTAL_MB))
# total memory used
TOTAL_USED_MEM_MB=$((MEM_USED_MB + SWAP_USED_MB))
# percentages
MEM_PCT=$((MEM_USED * 100 / MEM_TOTAL))
SWAP_PCT=$((SWAP_TOTAL > 0 ? SWAP_USED * 100 / SWAP_TOTAL : 0))
TOTAL_PCT=$((TOTAL_USED_MEM_MB * 100 / TOTAL_MEM_MB))

################################################################################
# srcds system
################################################################################

srcds_system() {
  dialog --no-collapse --msgbox "$(

    printf "%-16s %s\n" "Users........:" "$USERS ($(users))"
    printf "%-16s %s\n" "Hostname.....:" "$HOST"
    printf "%-16s %s\n" "Uptime.......:" "$UPTIME"
    printf "%-16s %s\n" "Load Avg.....:" "$LOAD"
    printf "%-16s %s\n\n" "IP Address...:" "$IP"

    printf "%-16s %s\n" "CPU Model....:" "$CPU_MODEL"
    printf "%-16s %s°C (%s)\n" "CPU Temp.....:" "$CPU_TEMP" "$CPU_TYPE"
    printf "%-16s %s°C (%s)\n\n" "Battery Temp.:" "$BATTERY_TEMP" "$BATTERY_TYPE"

    printf "%-16s %.1f GB / %.1f GB (%s%%)\n\n" \
      "Memory Used..:" "$MEM_USED_MB" "$MEM_TOTAL_MB" "$MEM_PCT"
    "Swap Used....:" "$SWAP_USED_MB" "$SWAP_TOTAL_MB" "$SWAP_PCT"

    echo "Disk Usage...:"
    printf "  %-12s %6s %6s %6s\n" "Mount" "Used" "Total" "Use%"
    printf "  %-12s %6s %6s %6s\n" "-----" "----" "-----" "----"

    df -BGB | awk 'NR>1 && $1 !~ /tmpfs|udev/ {
        printf "  %-12s %6s %6s %6s\n", $6, $3, $2, $5
      }'
  )" 0 0
}

# END
