#!/bin/bash

################################################################################
#
# SRCDS Tools & Options
# Author: Daedalus-code
#
# License: GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

# users, host, uptime, load, ip, cpu model
USERS=$(who | wc -l)
HOST=$(hostname)
UPTIME=$(uptime -p)
LOAD=$(cut -d' ' -f1-3 /proc/loadavg)
IP=$(hostname -I | awk '{print $1}')
CPU_MODEL=$(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo | xargs)

# load, srcds, screen pid
SYSTEM_LOAD="$(awk '{ print $1,$2,$3 }' /proc/loadavg)"
# get number of CPU cores
CPU_CORES=$(nproc)

# read individual load numbers into variables
read LOAD1 LOAD2 LOAD3 <<<"$SYSTEM_LOAD"

# calculate average load
AVG_LOAD=$(awk -v l1="$LOAD1" -v l2="$LOAD2" -v l3="$LOAD3" 'BEGIN { print (l1+l2+l3)/3 }')
# convert to percentage
LOAD_PCT=$(awk -v avg="$AVG_LOAD" -v cores="$CPU_CORES" 'BEGIN { printf "%.2f", (avg/cores)*100 }')

################################################################################
# thermals
################################################################################

BATTERY_TEMP_RAW=$(</sys/class/thermal/thermal_zone0/temp)
CPU_TEMP_RAW=$(</sys/class/thermal/thermal_zone1/temp)

BATTERY_TEMP=$((BATTERY_TEMP_RAW / 1000))
CPU_TEMP=$((CPU_TEMP_RAW / 1000))

BATTERY_TYPE=$(</sys/class/thermal/thermal_zone0/type)
CPU_TYPE=$(</sys/class/thermal/thermal_zone1/type)

################################################################################
# memory
################################################################################

# read RAM
MEM_TOTAL=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
MEM_AVAILABLE=$(awk '/MemAvailable/ {print $2}' /proc/meminfo)
# read swap
SWAP_TOTAL=$(awk '/SwapTotal/ {print $2}' /proc/meminfo)
SWAP_FREE=$(awk '/SwapFree/ {print $2}' /proc/meminfo)
SWAP_USED=$((SWAP_TOTAL - SWAP_FREE))
# RAM used
MEM_USED=$((MEM_TOTAL - MEM_AVAILABLE))
# convert to MB
MEM_TOTAL_MB=$((MEM_TOTAL / 1024))
MEM_USED_MB=$((MEM_USED / 1024))
SWAP_TOTAL_MB=$((SWAP_TOTAL / 1024))
SWAP_USED_MB=$((SWAP_USED / 1024))
# total memory
TOTAL_MEM_MB=$((MEM_TOTAL_MB + SWAP_TOTAL_MB))
# total memory used
TOTAL_USED_MEM_MB=$((MEM_USED_MB + SWAP_USED_MB))
# percentages
MEM_PCT=$((MEM_USED * 100 / MEM_TOTAL))
SWAP_PCT=$((SWAP_TOTAL > 0 ? SWAP_USED * 100 / SWAP_TOTAL : 0))
TOTAL_PCT=$((TOTAL_USED_MEM_MB * 100 / TOTAL_MEM_MB))

################################################################################
# network
################################################################################

# get primary network interface (skip loopback)
NET_IFACE=$(ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -n1)

# get RX and TX bytes in MB
RX_BYTES=$(</sys/class/net/"$NET_IFACE"/statistics/rx_bytes)
TX_BYTES=$(</sys/class/net/"$NET_IFACE"/statistics/tx_bytes)
RX_MB=$(awk -v b="$RX_BYTES" 'BEGIN {printf "%.2f", b/1024/1024}')
TX_MB=$(awk -v b="$TX_BYTES" 'BEGIN {printf "%.2f", b/1024/1024}')

# get link speed (requires ethtool)
if command -v ethtool >/dev/null 2>&1; then
  LINK_SPEED=$(ethtool $NET_IFACE 2>/dev/null | awk -F: '/Speed/ {gsub(" ","",$2); print $2}')
else
  LINK_SPEED="N/A"
fi

################################################################################
# space
################################################################################

SPACE_TOTAL=$(df -BG / | awk 'NR==2 {print $2}')
SPACE_USED=$(df -BG / | awk 'NR==2 {print $3}')
SPACE_FREE=$(df -BG / | awk 'NR==2 {print $4}')
SPACE_PCT=$(df -BG / | awk 'NR==2 {print $5}')

################################################################################
# srcds system
################################################################################

srcds_system() {
  dialog --no-collapse --msgbox "$(
    # system
    printf "%-14s %s\n" "Hostname.....:" "$HOST"
    printf "%-14s %s\n" "Users........:" "$USERS ($(users))"
    printf "%-14s %s\n" "Uptime.......:" "$UPTIME"
    printf "%-14s %s\n" "Load Avg.....:" "$LOAD"
    printf "%-14s %s\n\n" "IP Address...:" "$IP"
    # network
    printf "%-14s %s\n" "Interface....:" "$NET_IFACE"
    printf "%-14s %s\n" "Speed........:" "$LINK_SPEED"
    printf "%-14s %s\n" "Download.....:" "${RX_MB}MB"
    printf "%-14s %s\n\n" "Upload.......:" "${TX_MB}MB"
    # cpu temperatures
    printf "%-14s %s\n" "CPU Model....:" "$CPU_MODEL"
    printf "%-14s %s°C (%s)\n" "CPU Temp.....:" "$CPU_TEMP" "$CPU_TYPE"
    printf "%-14s %s°C (%s)\n\n" "Battery Temp.:" "$BATTERY_TEMP" "$BATTERY_TYPE"
    # memory
    printf "%-14s %.1f MB / %.1f MB (%s%%)\n" \
      "Memory Used..:" "$MEM_USED_MB" "$MEM_TOTAL_MB" "$MEM_PCT"
    printf "%-14s %.1f MB / %.1f MB (%s%%)\n\n" \
      "Swap Used....:" "$SWAP_USED_MB" "$SWAP_TOTAL_MB" "$SWAP_PCT"
    # disk
    printf "%-14s %s\n" "Disk Total...:" "$SPACE_TOTAL"
    printf "%-14s %s (%s)\n" "Disk Used....:" "$SPACE_USED" "$SPACE_PCT"
    printf "%-14s %s\n" "Disk Free....:" "$SPACE_FREE"
  )" 0 0
}

# END
